Google sign in
MichalZonis/Tripplan pull request #6
Opened 2023-11-19 15:26 UTC by Smichmich

dont approve this

2023-11-21 11:56 UTC, MichalZonis commented on client/src/app/login/login.component.html
> +<button id="googleSignInButton" (click)="login()">Google</button>
אם הזדהות גוגל לא עובדת אז הכפתור הזה הוא הזדהות שם משתמש וסיסמה?

2023-11-21 11:56 UTC, MichalZonis commented on client/src/app/login/login.component.ts
> +    google.accounts.id.initialize({
זורק לי שגיאה כל כמה ניסיונות שהוא לא יודע מה זה ID, מאיפה הוא מביא את google?

2023-11-21 15:28 UTC, Smichmich commented on server/controllers/auth.js
> +          error: "Username or password is incorrect",
תוקן בcommit  ייעודי

2023-11-24 16:41 UTC, MichalZonis requested changes

2023-11-24 16:41 UTC, MichalZonis commented on client/src/app/login/login.component.ts
> +  logout(): void {
שיעשה אחר כך redirect גם מלוגין וגם מרג'יסטר

2023-11-26 07:26 UTC, Smichmich commented on server/server.js
> +const cookieParser = require("cookie-parser");
local storage
הסרתי את הקוד המיותר

2023-11-26 07:27 UTC, Smichmich commented on server/config/database.config.js
רבתי איתו שהוא יעבוד (בסוף זה היה ההחלפה של localhost ב127.0.0.1)
החזרתי את השם של הדיבי

2023-11-26 08:30 UTC, Smichmich commented on client/src/app/login/login.component.ts
> +  logout(): void {
אין לי navbar בbranch הזה
הוספתי את הredirect גם מהתחברות רגילה, גם הרשמה וגם דרך גוגל

2023-11-26 08:30 UTC, Smichmich commented on client/src/app/login/login.component.scss
אין שימוש באנגולר מטריאל, רק bootstrap

2023-11-26 08:36 UTC, Smichmich commented on client/src/app/authentication.service.ts
מה הכוונה שימוש עקבי בhttp client? אם את מתכוונת לפונקציה של התחברות עם גוגל, תקראי את ההערה מעליה. אם לא אשמח לפירוט
איך לעשות pull מהmaster? למה הכוונה?

2023-11-26 09:30 UTC, Smichmich commented on client/src/app/login/login.component.html
> +<button id="googleSignInButton" (click)="login()">Google</button>
כבר לא רלוונטי, בדיקתך

2023-12-14 20:58 UTC, MichalZonis approved these changes

2023-12-14 20:58 UTC, merged